# Generated by Django 4.2 on 2025-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('required_skills', models.JSONField()),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('min_experience_years', models.IntegerField(default=0)),
            ],
        ),
    ]
