# Generated by Django 4.2 on 2025-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_parsed_json_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_warnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
