# Generated by Django 4.2 on 2025-09-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resumeskill_resumeproject_resumeexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
